#!/bin/bash

echo "Checking for dependency changes..."
(cd arm-dependencies || exit 1; git pull origin main)

# shellcheck disable=SC2237
if ! [[ -z $(git diff arm-dependencies) ]]; then
    echo "Updating dependencies..."
	git commit -m "updated dependencies" -- arm-dependencies
fi
