dist: focal
language: python
python:
  - "3.7"
before_install:
  - sudo apt-get install libgnutls28-dev
install: "pip install -r requirements.txt"
script:
  - flake8 arm
  - coverage run arm/ripper/main.py
  - coverage run arm/runui.py
script:
  - flake8 arm
after_success:
  - bash <(curl -s https://codecov.io/bash)
  - codecov
  - curl -s https://codecov.io/bash > codecov.sh
  - bash codecov.sh -t $CODECOV_TOKEN
