# Automatic Ripping Machine Docker Compose File
version: '3'

services:
  # Image for Automatic Ripping Machine
  arm_main:
    build:
      context: ./
      dockerfile: Dockerfile
    image: automaticrippingmachine/automatic-ripping-machine:3.0
    ports:
      - 8080:8080
    environment:
      - ARM_UID=1001    # Set this to the ARM user id
      - ARM_GID=1001    # Set this to the ARM user group id
      - MYSQL_IP=arm-db
      - MYSQL_USER=arm
      - MYSQL_PASSWORD=example
    volumes:
      # Volumes for ARM 'local directory':'ARM container directory - DON'T CHANGE THESE'
      - /home/arm:/home/arm
      - /home/arm/music:/home/arm/music
      - /home/arm/logs:/home/arm/logs
      - /home/arm/media:/home/arm/media
      - /home/arm/config:/etc/arm/config
#    devices:
#      - "/dev/sr0:/dev/sr0"
#      - "/dev/sr1:/dev/sr1"
      #- "/dev/sr2:/dev/sr2"
      #- "/dev/sr3:/dev/sr3"
      #- "/dev/sr4:/dev/sr4"
      #- "/dev/sr5:/dev/sr5"
    depends_on:
      - arm-db
    networks:
      - arm-network
    restart: unless-stopped

  # Image for the Automatic Ripping Machine Database, using MySql
  arm-db:
    image: mysql:latest
    container_name: arm-db
    user: 1001:1001                     # Set this to the arm user, $ id arm
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: arm
      MYSQL_USER: arm
      MYSQL_PASSWORD: example
    volumes:
      # Volumes for ARM db 'local directory':'Mariadb directory - DON'T CHANGE'
      - /home/arm/db:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - arm-network
    restart: unless-stopped

networks:
  arm-network: