# Automatic Ripping Machine Docker Compose File
version: '3'

services:

  # Image for Automatic Ripping Machine
  arm:
    build:
      context: ./
      dockerfile: Dockerfile
    image: result/latest
    container_name: automatic-ripping-machine
    depends_on:
    - arm-db
    networks:
      - arm-network
    environment:
      - ARM_UID=1001    # Set this to the ARM user id
      - ARM_GID=1001    # Set this to the ARM user group id
      - MYSQL_IP=arm-db
      - MYSQL_USER=arm
      - MYSQL_PASSWORD=example
    volumes:
      - "/home/arm:/home/arm"
      - "/home/arm/Music:/home/arm/Music"
      - "/home/arm/logs:/home/arm/logs"
      - "/home/arm/media:/home/arm/media"
      - "/home/arm/config:/etc/arm/config"
    ports:
      - 8080:8080
#    devices:
#      - "/dev/sr0:/dev/sr0"
#      - "/dev/sr1:/dev/sr1"
      #- "/dev/sr2:/dev/sr2"
      #- "/dev/sr3:/dev/sr3"
      #- "/dev/sr4:/dev/sr4"
      #- "/dev/sr5:/dev/sr5"
    restart: unless-stopped

  # Image for the Automatic Ripping Machine Database, using MySql
  arm-db:
    image: mysql
    container_name: arm-db
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - arm-network
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: arm
      MYSQL_USER: arm
      MYSQL_PASSWORD: example
    restart: unless-stopped

networks:
  arm-network: