name: Create release

on:
  # Triggers the workflow on push or pull request events but only for the v2.5.0_dev branch
  push:
    branches: main

jobs:
  release:
    name: Release pushed tag
    runs-on: ubuntu-22.04
    steps:         
      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ $GITHUB_REF_NAME }}
        run: |
          gh release create "$tag" \
              --repo="$GITHUB_REPOSITORY" \
              --title="${GITHUB_REPOSITORY#*/} ${tag#v}" \
              --generate-notes
