name: publish-docker-image

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
    # run every day at midnight
    schedule:
        - cron: '0 0 * * *'
    push:
        branches: [ docker ]
    pull_request:
        branches: [ docker ]
    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

env:
    # Use docker.io for Docker Hub if empty
    REGISTRY: ghcr.io
    # use DOCKERHUB_USERNAME as the name maybe different from the github username
    IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/automatic-ripping-machine
    TAG: latest

jobs:
    build:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write

        steps:
            -
                name: Checkout repository
                uses: actions/checkout@v2

